/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/execroot/ngrx/modules/store/src/models.ts:
/** @const */
var ngrx$modules$store$src$models = {};
/**
 * @extends {ngrx$modules$store$src$models.Action}
 * @template T
 * @record
 * @struct
 */
ngrx$modules$store$src$models.TypedAction = function() {};
/** @type {?} */
ngrx$modules$store$src$models.TypedAction.prototype.type;
